### PR TITLE
Styling, Levelling, and Tabs

### PR DESCRIPTION
**Pull request by LunarGem**
Putting in my work on styling, levelling, and the tabbed menu so the styling sass can be compiled and I can see if everything is fixed.

### CODE REVIEW

**Comment by Suds-p** [comment]
Lovin' the interface so far! Just wondering...should the battle messages eventually pop up in the log, or as toasts or something?

**Comment by LunarGem** [comment]
They will be in the log, I've made some changes in my recent commits to my branch and I was going to do the main infobar and then fix that. Toasts I was thinking for found items, levelling up, new areas unlocking, (puzzles appearing?), new story parts, the rarer stuff. If you're fighting fast and we made them toasts, they'd pile up pretty high on the side of the screen. I've got the log as a Materialize card now and I thought I'd just make it scrollable. Here's a shot of what my branch looks like:
image

**Comment by Suds-p** [comment]
Ahh gotcha. Should I copy over your current version and add my rest() fix in, so it's not a hassle to pull and merge?

**Comment by LunarGem** [comment]
Sure, why not. Just two more things until we're ready for functionality anyways.

**Pull request merged**
